### ISSUE TITLE
When I up to V2.0,I can't get any information

### ISSUE THREAD

**Issue by 02114** [bitfocus/companion-module-tslproducts-umdlistener#1]
When conpanion work in v2.0,it can get UMD.
When companion up to V3.0 and listener v2.0.It can't work.
This is the error⬇️
Error occurred setting yo tally listner:TypeError :a.createparser is not a function.

**Comment by benturnbull1991** [comment]
I am experiencing the same issue using v3 Stable and also the latest v3 Beta. 

@josephdadams I'm not sure if you can identify the issue? Thanks very much. 

Instance/Wrapper/tslumd-listener:` Error occurred setting up Tally Listener: TypeError: a.createParser is not a function

**Comment by josephdadams** [comment]
I just pushed v2.0.1 of this module, perhaps this will help.

**Comment by comebacktomorrow** [comment]
I just upgraded to 3.1.0+6080 beta with 2.0.1 of the listener to try and deal with this issue - I'm sad to say that the issue still exists. I also tried deleting instances of it as well, just in case.
